/*Add Categories*/
INSERT INTO category (category_name)
VALUES ("Chair");
INSERT INTO category (category_name)
VALUES ("Controller");
INSERT INTO category (category_name)
VALUES ("Boardgames");
INSERT INTO category (category_name)
VALUES ("Headphone");
INSERT INTO category (category_name)
VALUES ("Monitor");
INSERT INTO category (category_name)
VALUES ("Video Games");

/* Add Products*/
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Secretlab Titan 2020 Series","The larger cousin of the Secretlab OMEGA. The Secretlab TITAN is renowned for its ample space in addition to customization at the highest level. To give you greater comfort, support, reliability and personalization, the new 2020 Series features multiple improvements that will exceed the expectations of even the most discerning. For an uncompromising experience that lasts for endless hours, this elite award-winning chair is unquestionably the gold standard you need.","img/PID1.png",99,1);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Respawn Sidewinder Gaming Chair","There’s no doubt you’re in command when you’re sitting in the RESPAWN Sidewinder Gaming Chair. This gaming chair is sleek and stylish, from front to back. The chair features a plastic outer shell with an eye-popping colour inlay that grabs your attention and continues to the front with premium stitched contrasting colour overlays in PU leather. Not just good looking, this chair features durable foam support, with extra layers in the integrated headrest and lumbar support area for lasting, all-hours comfort. Simply push back to tilt your chair with the weight-activated tilt control and lock into various recline positions with the back angle lock. ","img/PID2.png",379.00,1);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("OFM Essentials Racing Chair ESS-3085","Relax at your desk even during long workdays with this Essentials by OFM racing-style gaming chair. The tall back and padded headrest let you lean back in comfort, while curved, segmented cushions deliver plush support.","img/PID3.png",149.99,1);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Xbox Elite Wireless Controller Series 2","All new Elite 2 controllers purchased through an authorized retailer are covered by a 1-year manufacturer warranty, regardless of purchase date. All warranty-related inquiries should be raised directly with Microsoft Support","img/PID4.png",179.00,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Xbox One Wireless Controller","Compatible with Xbox One, Xbox One S, and Windows 10, Includes Bluetooth technology for gaming on Windows 10 PCs and tablets, Stay on target with textured grip, Get up to twice the wireless range compared to previous Xbox One Controllers (tested using the Xbox One S Console)","img/PID5.png",164.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Razer Wolverine Ultimate: 6","ADVANCED CUSTOMIZABILITY FOR ULTIMATE CONTROL Our goal was to design the ultimate Xbox One controller, one adaptable to any gamer. We started with optimized ergonomics that stay comfortable after hours of practice, and interchangeable parts that adapt to your playstyle. Then we added Razer Chroma lighting and a suite of remappable buttons and triggers that allow you to change your layout and execute advanced techniques with ease. What you get is the most versatile and customizable","img/PID6.png",239.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Scuf Prestige Red","Back control functions are the determining factor for competitive gamers. SCUF Prestige Wireless includes 4 paddles that can be mapped to 14 Controller functions: A, B, X, Y, left stick, right stick, entire d-pad, menu, view, left bumper, and right bumper.","img/PID7.png",181.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("PDP Wired Controller for Xbox One","Non-slip grips, textured trigger buttons, and textured shoulder buttons give you premium tactile control. Vibration feedback system with impulse triggers make the game you're playing come alive in your hands. Vibration feedback system with impulse triggers make the game you're playing come alive in your hands ","img/PID8.png",34.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Thrustmaster eSwapX Pro Controller","Fully modular professional gamepad. New next-generation mini-sticks: a longer lifespan, and greater precision. Physical locking for triggers; direct Remapping of rear buttons. Technology and hot swap feature lets you swap a module with any other — at any point in a game","img/PID9.png",229.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("PowerA Wired FightPad for Xbox One","Six-button, arcade-style layout with Alps action buttons for precise control. Toggle switches for d-pad and shoulder buttons enable customizable options. Three swappable magnetic faceplates let you Switch up your style and color preferences","img/PID10.png",84.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Sony DualShock 4 Wireless Controller","The new multi-touch and clickable touch pad on the face of the DualShock 4 Wireless Controller opens up worlds of new gameplay possibilities for both newcomers and veteran gamers.","img/PID11.png",78.45,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Scuf Impact PlayStation","There’s controllers. And then, there’s SCUF. Every SCUF controller gives you the ability to use more of your hands to improve your speed and gameplay. Unlike standard controllers, the full-customization capabilities of Vantage 2 allows you to personalize every feature to fit your specific needs and style.","img/PID12.png",149.99,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Nacon Revolution Unlimited Pro Controller","Works with a Bluetooth receiver offering high performance gameplay with the audio chat feature. Includes a rechargeable li-polymer 1300 mah battery (autonomy 7h). Plug & play functionality with integrated DualShock 4 controls**, enhanced dual stick control with 46° amplitude and manually customise the 4x shortcuts buttons!","img/PID13.png",393.96,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Razer Raiju Ultimate Wireless PS4 Controller","With latest firmware 1.05 update (see video) for optimal performance. Razer mecha-tactile action buttons, soft cushioned touch with tactile feedback. Interchangeable thumbsticks, D-pad and quick control panel for advanced customisation. Enhanced App configuration to easily fine-tune control options", "img/PID14.png",260.32,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Hori Mini Wired Gamepad","Built for young gamers, the Officially Licensed mini wired gamepad for PS4 systems is Designed to fit smaller hands while providing the same great gaming experience you have come to expect with PS4 systems.","img/PID15.png",61.23,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("ASTRO Gaming C40 TR Controller - PlayStation 4","Ready for any environment, the TR line of ASTRO Gaming products deliver Premium design and performance for every type of Gamer. Optimum rear button layout for superior ergonomics improves Precision during Critical moments. Mappability streamlines the Controller for any genre and playstyle while improving response time.","img/PID16.png",574.33,2);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Cards Against Humanity","Cards Against Humanity is a party game for horrible people. This is the main game. Buy this first. Contains 500 white cards and 100 black cards for maximum replayability. Includes a booklet of sensible game rules and preposterous alternate rules. America's #1 gerbil coffin.","img/PID17.png",25.00,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Hedbanz Adulting","MILLENNIAL PARTY GAME: Hedbanz Adulting is the fun, fast-paced question game of “What am I?” Players each wear a headband with a card and ask as many “yes” or “no” questions as they can in 90 seconds to try to figure out what’s on their head! 7 NEW CARD CATEGORIES: With millennial-themed categories including a charades category, players guess if they’re a binge-worthy TV show, celebrity, profession, a trendy app and more! Earn points with every correct guess. The first player to 5 points wins!","img/PID18.png",13.38,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Catan Board Game","STRATEGY GAME: Trade, build and settle the Island of CATAN in this addictively fun strategy game previously called Settlers of CATAN. Players control their own civilization and look to spread across a modular hex board in a competition for victory points. FUN GAME WITH COUNTLESS REPLAY OPPORTUNITIES: The completely variable board provides great value through nearly limitless replayability. You will never have to play the same game twice. Looking for new adventures? Try CATAN expansions (Note: Expansions require CATAN base game to play).","img/PID19.png",41.27,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Clue Game","Clue game includes 2 versions, the Mansion game and the Boardwalk game. 2-sided gameboard. Features updated rooms, weapons, guests. Yellow murder envelope, Clue sheet notepad, 6 character tokens, 6 weapon tokens, 27 black Clue cards, 3 red bonus cards, 2 dice and instructions","img/PID20.png",9.99,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Ticket to Ride","STRATEGY GAME: Build your tracks across the United States in this fast-paced and strategic board game. Connect iconic North American cities across a map of the 20th-century USA and build your train routes to earn points. FUN ADVENTURE GAME: Ticket to Ride is a cross-country train adventure game in which players collect and play matching train cards to claim railway routes connecting cities through North America! LOOKING FOR NEW ADVENTURES? Try Ticket to Ride expansions (Note: Expansions require Ticket to Ride Board Game to play)","img/PID21.png",43.99,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Adult Loaded Questions","The hilarious adult party version of the classic ‘who said what’ game. For 4 6 players / ages 17+. Features 308 new and classic Adult Loaded Questions, all new design, and added game play features/components for a laughter filled Game Night. Questions include: What is an instant mood killer? / What word sounds dirty but isn’t? / What TV show would you watch if it included full nudity.","img/PID22.png",13.99,3);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("SteelSeries Arctis 7P/7X","Over-ear headphones designed to provide a full seal that blocks out external distractions and a comfortable fit for your long PC gaming sessions. Designed for PlayStation 5 and also compatible with PlayStation 4, PC, Android, and Nintendo Switch. Lossless 2.4 GHz wireless audio designed for ultra-low latency gaming","img/PID23.png",189.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("HyperX Cloud Stinger","No.1 selling PC gaming headset in the U.S. - Source: The NPD Group, Inc., U.S. retail tracking service, PC headsets, gaming designed, based on units, January-December 2019. Lightweight headset (275 gram) with 90-degree rotating ear cups provide a snug fit that conforms to your head","img/PID24.png",69.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Xbox Wireless Headset","Game loud and clear with the Xbox Wireless Headset, surround yourself with spatial sound technologies including Windows Sonic, Dolby Atmos, and DTS Headphone:X. Auto-mute and voice isolation reduce background noise and allow for crystal-clear chat. The flexible, lightweight design with an adjustable headband makes for a more comfortable experience during extended play sessions while rotating earcup dials provide a quick and intuitive way to adjust volume and game/chat balance. ","img/PID25.png",129.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Razer BlackShark V2","Over-ear headset offers powerful sound with deep bass, while its advanced passive noise cancellation gives you uninterrupted focus. Wired headset with USB adapter and 3.5mm plug gives it the ability to work with different devices. 50mm titanium Razer Triforce drivers with 12Hz-28KHz frequency response guarantee impressive sound quality ","img/PID26.png",139.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Logitech G Pro X","Over-ear headset features memory foam ear pads with premium passive noise-canceling leatherette covers or soft, breathable velour covers for customizable comfort. Wired design boasts a 2-metre cord and 3.5mm plug for universal compatibility. PRO-G 50mm drivers and Neodymium magnets deliver stunning, true-to-life sound. Blue VO!CE software and next-gen 7.1 surround sound enable professional-quality voice comms ","img/PID27.png",149.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Razer Kaira Pro","CONSOLE. MOBILE. COMBINED: Enjoy cutting-edge audio performance that embraces the future of Xbox. Enter the Razer Kaira Pro—a wireless headset for Xbox Series X|S and mobile gaming. Fitted with our best drivers and headset mic, experience stellar sound and voice chat for unrivalled console and mobile gaming.","img/PID28.png",199.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("SteelSeries Arctis 1 Wireless Gaming Headset","Over-ear gaming headset features cloth ear cushions to keep you comfortable during marathon gaming sessions. Wireless technology offers lag-free 2.4G lossless audio and comes with a USB-C dongle so you can connect with Nintendo Switch and Android devices. High-performance speakers, 40mm drivers, neodymium magnets, and a frequency response of 20 Hz - 20 kHz ensure you hear every game in life-like detail","img/PID29.png",119.99,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Turtle Beach Elite Atlas Aero","Waves Nx 3d Audio - Waves Nx delivers an immersive 3D audio experience by providing pinpoint location accuracy and lifelike sound enabling gamers to be inside the game. By recreating real-world sounds in a virtual space, Waves Nx 3D Audio surrounds the gamer in a natural environment creating a more accurate spatial scene so that they can easily pick out important sounds to help them win. ","img/PID30.png",212.71,4);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("The LG UltraGear 27GN950-B","27” FHD (1920 x 1080) IPS Display. NVIDIA G-Sync Compatible. Adaptive-Sync Technology. 144Hz Refresh Rate, 1ms Motion Blur Reduction. Height / Pivot / Tilt Adjustable Stand","img/PID31.png",799.00,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("GIGABYTE G27Q Gaming Monitor","27” 2560x1440 IPS Display with 144Hz Refresh Rate, 1ms (MPRT) Response Time. Smooth Gameplay with AMD FreeSync Premium. Studio Grade VESA Display HDR400 and 92% DCI-P3 (120% sRGB) Color Gamut. GIGABYTE Classic Tactical Features with OSD Sidekick","img/PID32.png",395.75,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Pixio PX277 Prime","27 inch WQHD (Wide Quad High Definition) 2560 x 1440p Ultimate eSports Gaming Monitor. IPS Panel, HDR, 350nit Brightness, Increases the dynamic range between black and white to showcase incredible clarity and details. 165Hz Refresh Rate, FreeSync (Range 48-165Hz @DisplayPort, 48-144Hz @HDMI), G-Sync compatible. Flicker Free, Low Blue Light, VESA 100x100, Connectivity: 1 x DisplayPort (165Hz), 2 x HDMI (144Hz), 1 x Audio Out. Compatible with Console & PC platforms. Includes DP cable, power cable and stand.","img/PID33.png",807.69,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("The Acer Predator X38","37.5 UltraWide QHD+ (3840 x 1600) Widescreen Agile-Splendor IPS NVIDIA G-SYNC Display | 2300R Curved Display with 21:9 Aspect Ratio. ZeroFrame Design | Up to 175Hz Refresh Rate | Response Time: 1ms (G to G) - Up to 0.3ms (G to G). High Brightness and Contrast with VESA Certified DisplayHDR 400 | DCI-P3 98% Wide Color Gamut | Delta E<2. Predator GameView with 8 modes | 2 Speakers, 7 Watts Per Speaker. Ports: 1 x Display Port 1.4, 1 x HDMI v2.0, Audio Out & 4 x USB 3.0 Ports (HDMI, Display Port and USB Cables included)","img/PID34.png",2999.99,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("ROG STRIX XG17AHPE Portable","17.3 Full HD (1920x1080) IPS portable gaming monitor with 240Hz refresh rate and 3ms (GTG) for super-smooth gaming visual. Hybrid-signal USB-C and micro-HDMI ports provide versatile connectivity with smartphones, laptops, game consoles, cameras, tablets and more. Adaptive-sync to deliver a seamless, tear-free gaming experience. Built-in battery provides up to 3 hours at 240hz refresh rate. Smart Case optimized gaming scenarios on the go for console, smartphone, notebook","img/PID35.png",649.99,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Alienware 25 AW2521HF","A true 1ms response time blasts away ghosting and blurs for clear images with no artificial tricks needed. New, fast IPS technology helps maintain image clarity from every angle of the screen. Plus, with up to 99% sRGB color coverage, you have a wide array of colors in your arsenal. AMD FreeSync Premium and NVIDIA G-SYNC Compatible technology synchronizes the graphics and monitor, so you get epic, tear-free images that don't slow down your gameplay","img/PID36.png",299.00,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("ASUS ROG Swift PG259QN","24.5 - inches Full HD (1920 x 1080) Fast IPS panel and the world’s first 360Hz gaming monitor. ASUS Fast IPS technology enables a 1 ms response time (GTG) for sharp gaming visuals with high frame rates. NVIDIA G-SYNC processor provides smooth, tear-free gaming at refresh rates up to 360Hz. An intelligent cooling system featuring a custom heatsink to provide more surface area for heat exchange, ensuring efficient cooling during marathon gaming sessions","img/PID37.png",949.99,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("MSI Optix MPG341CQR","Curved gaming display (1800R) - the best gameplay immersion. Uwqhd high resolution - game titles will even look better, displaying more details due to the UWQHD resolution. Gamesense - conductive enables external game alerts via RGB LED lighting with the hottest competitive online games. 1ms response time - eliminate screen tearing and choppy frame rates. Hdr 400 - stunning visuals with the most criterion format","img/PID38.png",1002.99,5);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Red Dead Redemption 2","From the creators of Grand Theft Auto V and Red Dead Redemption, Red Dead Redemption 2 is an epic tale of life in America at the dawn of the modern age. America, 1899. The end of the wild west era has begun as lawmen hunt down the last remaining outlaw gangs. Winner of over 175 Game of the Year Awards","img/PID39.png",35.74,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Grand Theft Auto V","Will take full advantage of the power of new generation systems and PC to deliver across-the-board enhancements including increased resolution and graphical detail, denser traffic, greater draw distances, upgraded AI, new wildlife, and advanced weather and damage effects for the ultimate open world experience.The biggest, most dynamic and most diverse open world ever created and now packed with layers of new detail.","img/PID40.png",27.95,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("F1 2020","Create a driver, then choose a sponsor, an engine supplier, hire a teammate and compete as the 11th team on the grid. Build facilities and develop the team over time and drive to the top. New - two new races: hanoi circuit and circuit zandvoort","img/PID41.png",136.70,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("NBA 2K17","The #1 rated NBA video game simulation series for the last 15 years (Metacritic). The #1 selling NBA video game simulation series for the last 9 years (NPD). Over 85 awards and nominations since the launch of PlayStation 4 & Xbox One.","img/PID42.png",75.70,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Battlefield 1","Epic 64-Player Multiplayer Battles - Squad up with your friends and join in the most epic multiplayer battles in FPS history with up to 64 players. Fight as infantry, lead horse charges or take control of amazing vehicles on land, air and sea, from tanks and biplanes to the gigantic Behemoths.","img/PID43.png",24.70,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Forza Horizon 4","SEASONS CHANGE EVERYTHING. For the first time in the racing and driving genre, experience dynamic seasons in a shared open-world. Explore beautiful scenery, collect over 450 cars, and become a Horizon Superstar in historic Britain. (Some cars provided by online update.","img/PID44.png",54.99,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("FIFA 20","•	Volta Kick-Off: take your favorite professional teams back to the streets and compete in a number of Volta locations and match formats. Psg vs. Lyon in Paris, the Madrid derby in the streets of Spain, or Chelsea vs. Spurs in a London cage. Volta world: build up your Volta team by playing through single player matches against community generated squads in a variety of formats and locations. After each victory, Recruit any player from the opposing team, building your squad up in terms of both skill and chemistry","img/PID45.png",15.70,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("Metal Gear Solid V The Phantom Pain","Taking place nine years after the events of MGSV: Ground Zeroes and the fall of Mother Base, Snake a.k.a. Big Boss, awakes from a nine year coma. The game resumes the story in 1984, with the Cold War still as the backdrop, which continues to shape a global crisis. Snake’s journey takes him into a world where he is driven by a need for revenge and the pursuit of a shadow group, XOF. ","img/PID46.png",29.99,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("The Last of Us Remastered","Winner of over 200 Game of the Year awards. Explore a brutal post-pandemic world, fully realized with the power of PlayStation 4 system. Includes all DLC packs: over $30 in value. In-game cinematic commentary from the cast and creative director","img/PID47.png",19.99,6);
INSERT INTO product (product_name, product_description, product_image, product_price, category_id)
VALUES ("God of War","A New Beginning — His vengeance against the gods of Olympus far behind him, Kratos now lives as a man in the lands of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same. Second Chances — As mentor and protector to a son determined to earn his respect, Kratos is faced with an unexpected opportunity to master the rage that has long defined him. Questioning the dark lineage he’s passed on to his son, he hopes to make amends for the shortcomings of his past","img/PID48.png",19.99,6);

/*Add role*/
INSERT INTO role (role_name)
VALUES ("Admin");
INSERT INTO role (role_name)
VALUES ("Customer");

/*Add Customer*/
INSERT INTO customer (first_name,last_name,address,email,client_password,create_date,recent_login,role_id,privacy)
VALUES ("Kha","Hoang","3943 Quadra St","hoangdangnhatkha@gmail.com","password123",NOW(),NOW(),1,1);
INSERT INTO customer (first_name,last_name,address,email,client_password,create_date,recent_login,role_id,privacy)
VALUES ("Joshua","Bartolome","1111 Faifield Road","remuwutwut@gmail.com","password123",NOW(),NOW(),1,1);
INSERT INTO customer (first_name,last_name,address,email,client_password,create_date,recent_login,role_id,privacy)
VALUES ("Bao","Nguyen","3333 Pandora","dinhbaonguyen2004@gmail.com","password123",NOW(),NOW(),1,1);

